server:
    port: 4000

spring:
    cloud:
        gateway:
            routes:
            # demo
            - id: person
              predicates: 
                - Path=/api/demo/**
              uri: http://localhost:4001
              
            # app_user
            - id: user
              predicates:
                - Path=/api/user/**
              uri: http://localhost:4002